pub use groth16_bn254::{self, *}

msg Groth16Bn254VerifierMsg {
    // verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[1])
    #[selector = 0x43753b4d]
    VerifyProof {
        a_x: u256,
        a_y: u256,
        b_x_c1: u256,
        b_x_c0: u256,
        b_y_c1: u256,
        b_y_c0: u256,
        c_x: u256,
        c_y: u256,
        input: u256,
    } -> bool,
}

/// Stateless contract wrapper for the demo verifying key in `groth16_bn254`.
pub contract Groth16Bn254Verifier {
    recv Groth16Bn254VerifierMsg {
        VerifyProof {
            a_x,
            a_y,
            b_x_c1,
            b_x_c0,
            b_y_c1,
            b_y_c0,
            c_x,
            c_y,
            input,
        } -> bool {
            groth16_bn254::verifyProof(
                a: [a_x, a_y],
                b: [[b_x_c1, b_x_c0], [b_y_c1, b_y_c0]],
                c: [c_x, c_y],
                input: [input],
            )
        }
    }
}
